apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rabbitmq-main-config
  namespace: rabbitmq-instance-main-flux
spec:
  interval: 5m
  chart:
    spec:
      chart: main
      sourceRef:
        kind: GitRepository
        name: rabbitmq-instance
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2