apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq-main
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: rabbitmq-instance-main-flux
  sourceRef:
    kind: GitRepository
    name: rabbitmq-poc-gitops-flux-repo
  path: "./cluster-instance/env/main"
  prune: true
  timeout: 1m