apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: {{ .Values.exchange.name }}-exchange-{{ .Values.env }}
spec:
  name: {{ .Values.exchange.name }}-{{ .Values.env }} # name of the exchange
  type: fanout # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq-{{ .Values.env }}
    namespace: rabbitmq-instance-{{ .Values.env }}
