apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: user-consumer-producer
spec:
  tags:
    - policymaker
    - administrator
  rabbitmqClusterReference:
    name: rabbitmq-{{ .Values.env }}
    namespace: rabbitmq-instance-{{ .Values.env }}
  importCredentialsSecret:
      name: user-consumer-producer-secret # name of the secret
